site_name: Gimlet.io Documentation
theme:
  name: material

copyright: Copyright &copy; 2020 Laszlo Consulting Kft

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Concepts:
      - GitOps: concepts/gitops.md
      - Architecture: concepts/architecture.md
  - Setup:
      - Initial Setup: setup/initial-setup.md
      - Slack integration: setup/slack.md
      - Gimlet Agent: setup/agent.md
      - Gitops Repository: setup/gitops-repo.md
      - Master Template: setup/master-template.md
  - For Developers:
      - Deploying a new service: developers/deploy.md
      - .gimlet.yaml: developers/gimlet-yaml.md
      - Deployment workflows: developers/deploy-workflows.md
      - Rollback: developers/rollback.md
      - Deployment errors: developers/errors.md
  - Reference:
      - Deployment options: reference/options.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/laszlocph
