site_name: Gimlet.io
theme:
  name: material

copyright: Copyright &copy; 2020 Laszlo Consulting Kft

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Concepts:
      - GitOps: concepts/gitops.md
      - Architecture: concepts/architecture.md
  - Setup:
      - Self-host with Bitbucket Server: setup/bitbucket-server.md
      - Master Template: setup/master-template.md
  - For Developers:
      - Deploying a new service: developers/deploy.md
      - The repository UI: developers/ui.md
      - Deployment workflows: developers/deploy-workflows.md
      - .gimlet.yaml: developers/gimlet-yaml.md
      - Rollback: developers/rollback.md
  - Reference:
      - The GitOps repository: reference/gitops-repo.md
      - Deployment options: reference/options.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/laszlocph

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
